### ISSUE TITLE
Manually create schemas for benchmarking

### ISSUE THREAD

**Issue by megh-khaire** [megh-khaire/vulcanDB#7]
https://github.com/taoyds/spider 
https://data.cityofnewyork.us/browse?sortBy=most_accessed&utf8=%E2%9C%93 
https://www.kaggle.com/datasets
https://archive.ics.uci.edu/

**Comment by Arhan13** [comment]
These are a few schema that I created - [Doc](https://docs.google.com/document/d/110rE50Zqv57Wyln6EYJXeoVtTj-wweRmEnxyiaapsdU/edit)
